services:
  medinav:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: medinav:humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../:/ws/MediNav
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
