#!/usr/bin/env python3
"""CLI client: send a delivery order."""
import argparse
import sys

import rclpy
from rclpy.node import Node

from medinav_task.srv import Order


class OrderClient(Node):
    def __init__(self):
        super().__init__('order_client')
        self.cli = self.create_client(Order, '/medi/order')
        while not self.cli.wait_for_service(timeout_sec=2.0):
            self.get_logger().info('waiting for /medi/order ...')

    def send(self, ward: str, order_id: str = ''):
        req = Order.Request()
        req.ward = ward
        req.order_id = order_id
        future = self.cli.call_async(req)
        rclpy.spin_until_future_complete(self, future)
        return future.result()


def main():
    parser = argparse.ArgumentParser(description='Send MediNav delivery order')
    parser.add_argument('ward', nargs='?', default='ward_3')
    parser.add_argument('--order-id', default='')
    args = parser.parse_args()

    rclpy.init()
    node = OrderClient()
    res = node.send(args.ward, args.order_id)
    print(f'accepted={res.accepted} order_id={res.order_id} message={res.message}')
    node.destroy_node()
    rclpy.shutdown()
    sys.exit(0 if res.accepted else 1)


if __name__ == '__main__':
    main()
